# Generated by Django 5.2.5 on 2025-09-03 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('category_type', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], max_length=10, verbose_name='ประเภท')),
                ('icon', models.CharField(choices=[('💰', 'เงิน'), ('🏠', 'บ้าน'), ('🍕', 'อาหาร'), ('⛽', 'น้ำมัน'), ('🚗', 'รถยนต์'), ('🎬', 'ความบันเทิง'), ('👕', 'เสื้อผ้า'), ('💊', 'สุขภาพ'), ('📚', 'การศึกษา'), ('💼', 'ธุรกิจ'), ('🎁', 'ของขวัญ'), ('✈️', 'การเดินทาง'), ('📱', 'เทคโนโลยี'), ('🏦', 'ธนาคาร'), ('💳', 'บัตรเครดิต'), ('🛍️', 'ช้อปปิ้ง'), ('🏥', 'โรงพยาบาล'), ('🎵', 'ดนตรี'), ('⚡', 'สาธารณูปโภค'), ('🍽️', 'ร้านอาหาร')], default='💰', max_length=10, verbose_name='ไอคอน')),
                ('color', models.CharField(choices=[('#FF6B6B', 'แดง'), ('#4ECDC4', 'เขียวน้ำทะเล'), ('#45B7D1', 'ฟ้า'), ('#96CEB4', 'เขียวอ่อน'), ('#FECA57', 'เหลือง'), ('#FF9FF3', 'ชมพู'), ('#54A0FF', 'น้ำเงิน'), ('#5F27CD', 'ม่วง'), ('#00D2D3', 'ฟ้าใส'), ('#FF9F43', 'ส้ม'), ('#10AC84', 'เขียว'), ('#EE5A24', 'ส้มแดง'), ('#0ABDE3', 'ฟ้าอ่อน'), ('#C44569', 'แดงอ่อน'), ('#40739E', 'น้ำเงินเข้ม')], default='#FF6B6B', max_length=7, verbose_name='สี')),
                ('is_default', models.BooleanField(default=False, verbose_name='หมวดหมู่เริ่มต้น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ['category_type', 'name'],
                'unique_together': {('user', 'name', 'category_type')},
            },
        ),
    ]
